---
- name: Create Alertmanager config directory
  ansible.builtin.file:
    path: /etc/alertmanager/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy Alertmanager configuration file
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    owner: root
    group: root
    mode: '0644'
  notify: Reload Alertmanager config

- name: Run Alertmanager container in Podman pod
  containers.podman.podman_container:
    name: alertmanager
    pod: monitoring
    image: quay.io/prometheus/alertmanager
    state: started
    restart_policy: always
    volumes:
      - /etc/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:z
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--web.listen-address=:9093"

- name: Create Vector config directory when using Kafka or ServiceNow forwarder
  ansible.builtin.file:
    path: /etc/vector/
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: alertmanager_forwarder_mode | default('servicenow') != 'webhook'

- name: Deploy Vector configuration for selected forwarder
  ansible.builtin.template:
    src: "{{ 'vector_kafka.toml.j2' if alertmanager_forwarder_mode | default('servicenow') == 'kafka' else 'vector_servicenow.toml.j2' }}"
    dest: /etc/vector/vector.toml
    owner: root
    group: root
    mode: '0644'
  when: alertmanager_forwarder_mode | default('servicenow') != 'webhook'
  notify: Restart Alert forwarder

- name: Run Vector alert forwarder when using Kafka or ServiceNow
  containers.podman.podman_container:
    name: "{{ 'alertmanager2kafka' if alertmanager_forwarder_mode | default('servicenow') == 'kafka' else 'alertmanager2servicenow' }}"
    pod: monitoring
    image: "{{ alertmanager_forwarder_image | default('docker.io/timberio/vector:0.36.0-debian') }}"
    state: started
    restart_policy: always
    command:
      - "-c"
      - "/etc/vector/vector.toml"
    volumes:
      - /etc/vector/vector.toml:/etc/vector/vector.toml:z
  when: alertmanager_forwarder_mode | default('servicenow') != 'webhook'
