---

- name: Reload Alertmanager config
  ansible.builtin.uri:
    url: http://127.0.0.1:9093/-/reload
    method: POST
    status_code: 200,202
  listen: Reload Alertmanager config

- name: Restart Alert forwarder (stop)
  containers.podman.podman_container:
    name: "{{ 'alertmanager2kafka' if alertmanager_forwarder_mode | default('servicenow') == 'kafka' else 'alertmanager2servicenow' }}"
    state: stopped
  listen: Restart Alert forwarder

- name: Restart Alert forwarder (start)
  containers.podman.podman_container:
    name: "{{ 'alertmanager2kafka' if alertmanager_forwarder_mode | default('servicenow') == 'kafka' else 'alertmanager2servicenow' }}"
    state: started
  listen: Restart Alert forwarder
