---
- name: Manage Service Now incidents
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    short_description: "EDA Demo incident"
    description: "Incident created by EDA demo"
    impact: 2
    urgency: 2
    work_notes: "Updated by EDA demo"
    close_notes: "Issue automatically resolved by Event-Driven Ansible"
    incident_sys_id: ""
    alert_fingerprint: ""
  tasks:
    ################################################################################################
    ##############################   CREATING INCIDENTS  ###########################################
    - name: Prevent Duplicated incidents by looking up existing incident by correlation_id
      servicenow.itsm.incident_info:
        query:
          - correlation_id: "{{ alert_fingerprint | default('') }}"
        return_fields:
          - sys_id
          - number
          - state
      register: existing_inc
      tags:
        - create_incident

    # Create ServiceNow incident and set incident_sys_id so it's accessible in workflow or rulebook
    - name: Create a ServiceNow incident
      servicenow.itsm.incident:
        state: new
        caller: "System Administrator"
        short_description: "{{ short_description }}"
        description: "{{ description }}"
        impact: "{{ impact }}"
        urgency: "{{ urgency }}"
        other:
          correlation_id: "{{ alert_fingerprint | default('') }}"
      register: create_incident
      tags:
        - create_incident

    - name: Consolidate all facts and original event into set_stats
      ansible.builtin.set_stats:
        data:
          incident_sys_id: "{{ create_incident.record.sys_id }}"
          eda_event: "{{ original_event | default({}) }}"
      tags:
        - create_incident

    ################################################################################################
    ##############################   UPDATING INCIDENTS  ###########################################

    # Update state and work notes on ServiceNow incident
    - name: Update state and work notes on ServiceNow incident
      servicenow.itsm.incident:
        sys_id: "{{ incident_sys_id }}"
        state: 2 # In Progress
        other:
          work_notes: "{{ work_notes }}"
      tags:
        - update_incident
      register: update_incident

    ################################################################################################
    ##############################   RESOLVING INCIDENTS  ###########################################

    # Resolve the ServiceNow incident with resolution information
    - name: Resolve the ServiceNow incident
      servicenow.itsm.incident:
        sys_id: "{{ incident_sys_id }}"
        state: 6  # 6 = Resolved
        close_notes: >
          "{{ close_notes | default("Issue automatically resolved by Event-Driven Ansible") }}"
        close_code: "eda_resolved" # custom created close code (System Definition > Choice Lists) in SNOW
        other:
          resolved_by: "System Administrator"
      tags:
        - resolve_incident
      register: resolve_incident
